# ** Metadata/Options **
QUICKFIX_KEY_PREFIX="@quickfix-key"

QUICKFIX_COMMAND_OPTION="@quickfix-command"
QUICKFIX_POSITION="@quickfix-position"
QUICKFIX_OPTION="@quickfix-win"
QUICKFIX_HEIGHT_OPTION="@quickfix-height"
QUICKFIX_PERC_OPTION="@quickfix-perc-size"
REGISTERED_PANE_PREFIX="@quickfix-registered-pane"
REGISTERED_QUICKFIX_PREFIX="@quickfix-id"

# ** Default options **

QUICKFIX_DEFAULT_PERC_SIZE="20"
QUICKFIX_DEFAULT_HEIGHT="30"
QUICKFIX_DEFAULT_KEY="z"
QUICKFIX_DEFAULT_POSITION="bottom"
QUICKFIX_DEFAULT_COMMAND="$SCRIPTS_DIR/toggle.sh"

TMUX_VERSION_ALLOWED="2.2"
